# Generated by Django 5.1.1 on 2024-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/hobbies-activity-amusement-freetime-interest-concept-74926992.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.CharField(default='https://cdn-icons-png.freepik.com/512/12238/12238054.png', max_length=500),
        ),
    ]
