# Generated by Django 5.1.1 on 2025-01-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
