# Generated by Django 5.1.1 on 2025-02-18 20:21

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0005_skill_tag_contact_contact_subject_contact_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
