# Generated by Django 5.1.1 on 2025-02-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0006_alter_portfolio_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(default='genericproject.jpg', upload_to='project_pictures'),
        ),
    ]
